# Site settings
header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Blog  # <-- blog.md
    - name: Whatever  # <-- whatever.md

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: g.a.pourcel@rug.nl
      link: mailto:g.a.pourcel@rug.nl

  follow:
    - name: Twitter
      link: http://twitter.com/GuillaumeAP
      username: "@GuillaumeAP"
    - name: LinkedIn
      link: www.linkedin.com/in/guillaume-a-pourcel

# Build settings
remote_theme: eliottvincent/bay
